# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clientgui_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(579, 370)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 12, 541, 191))
        self.textBrowser.setObjectName("textBrowser")
        self.EnumirateBoard = QtWidgets.QPushButton(self.centralwidget)
        self.EnumirateBoard.setGeometry(QtCore.QRect(13, 203, 555, 32))
        self.EnumirateBoard.setObjectName("EnumirateBoard")
        self.CallPortMethod = QtWidgets.QPushButton(self.centralwidget)
        self.CallPortMethod.setGeometry(QtCore.QRect(13, 290, 555, 32))
        self.CallPortMethod.setObjectName("CallPortMethod")
        self.Name_sereal = QtWidgets.QComboBox(self.centralwidget)
        self.Name_sereal.setGeometry(QtCore.QRect(17, 267, 190, 32))
        self.Name_sereal.setCurrentText("")
        self.Name_sereal.setObjectName("Name_sereal")
        self.Port_type = QtWidgets.QComboBox(self.centralwidget)
        self.Port_type.setGeometry(QtCore.QRect(203, 267, 151, 32))
        self.Port_type.setObjectName("Port_type")
        self.Port = QtWidgets.QComboBox(self.centralwidget)
        self.Port.setGeometry(QtCore.QRect(349, 267, 100, 32))
        self.Port.setObjectName("Port")
        self.Method = QtWidgets.QComboBox(self.centralwidget)
        self.Method.setGeometry(QtCore.QRect(445, 267, 120, 32))
        self.Method.setObjectName("Method")
        self.GetBoardOfType_2 = QtWidgets.QLabel(self.centralwidget)
        self.GetBoardOfType_2.setGeometry(QtCore.QRect(20, 232, 191, 35))
        self.GetBoardOfType_2.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.GetBoardOfType_2.setAlignment(QtCore.Qt.AlignCenter)
        self.GetBoardOfType_2.setObjectName("GetBoardOfType_2")
        self.GetBoardOfType_3 = QtWidgets.QLabel(self.centralwidget)
        self.GetBoardOfType_3.setGeometry(QtCore.QRect(200, 232, 151, 35))
        self.GetBoardOfType_3.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.GetBoardOfType_3.setAlignment(QtCore.Qt.AlignCenter)
        self.GetBoardOfType_3.setObjectName("GetBoardOfType_3")
        self.GetBoardOfType_4 = QtWidgets.QLabel(self.centralwidget)
        self.GetBoardOfType_4.setGeometry(QtCore.QRect(340, 232, 111, 35))
        self.GetBoardOfType_4.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.GetBoardOfType_4.setAlignment(QtCore.Qt.AlignCenter)
        self.GetBoardOfType_4.setObjectName("GetBoardOfType_4")
        self.GetBoardOfType_5 = QtWidgets.QLabel(self.centralwidget)
        self.GetBoardOfType_5.setGeometry(QtCore.QRect(450, 232, 109, 35))
        self.GetBoardOfType_5.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.GetBoardOfType_5.setAlignment(QtCore.Qt.AlignCenter)
        self.GetBoardOfType_5.setObjectName("GetBoardOfType_5")
        self.Save_xml = QtWidgets.QPushButton(self.centralwidget)
        self.Save_xml.setGeometry(QtCore.QRect(13, 312, 555, 32))
        self.Save_xml.setObjectName("Save_xml")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Client-Server"))
        self.EnumirateBoard.setText(_translate("MainWindow", "Enumirate Board"))
        self.CallPortMethod.setText(_translate("MainWindow", "Call Port Method"))
        self.GetBoardOfType_2.setText(_translate("MainWindow", "Board Of Type"))
        self.GetBoardOfType_3.setText(_translate("MainWindow", "Enumirate\n"
"Board Ports"))
        self.GetBoardOfType_4.setText(_translate("MainWindow", "Board Ports\n"
"Of Type"))
        self.GetBoardOfType_5.setText(_translate("MainWindow", "Port\n"
"Capabilities"))
        self.Save_xml.setText(_translate("MainWindow", "Save a description in XML"))
